#!/usr/bin/python
import time
import requests
import urllib2
import json

header = {
  'Content-Type': 'application/json',
  'X-Auth-Email': 'xxx@xxx',
  'X-Auth-Key': 'xxxxxx',
}
data = {
  "type": "A",
  "name": "xxxx",
  "content": "",
  "ttl": "120",
  "proxied": "true"
}


while True:
  showip =  urllib2.urlopen("http://icanhazip.com").read()
  data['content'] = showip
  timel = time.strftime("%Y-%m-%d %H:%M")
  if checkip != showip:
       response = requests.put('https://api.cloudflare.com/client/v4/zones/a2787cb767c3b45965cd1d1b38ff3d6c/dns_records/2580ac100328c870f6297f759293390f', headers=header, data=json.dumps(dat$
       print(response)
       print(response.content)
       checkip = showip
  if checkip == showip:
       print showip
  time.sleep(300
